---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: About Me
- type: document
  path: _about/*
  label: About
- type: heading
  label: Projects
- type: directory
  path: _projects
  label: Projects
  create: documents
  match: "**/*"
  templates:
  - project
- type: heading
  label: Posts
- type: directory
  path: _posts
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - post
- type: heading
  label: Contact
upload_dir: public
public_path: "/public"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: preview
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
