---
new_page_extension: md
auto_deploy: false
admin_path: "/public/admin"
webhook_url: 
sections:
- type: directory
  path: content/pages
  label: Pages
  create: documents
  match: "**/*"
  templates:
  - about-page
  - blog-page
  - contact-page
  - home-page
  - work-page
- type: directory
  path: content/work
  label: Works
  create: documents
  match: "**/*"
  templates:
  - work-item
- type: directory
  path: content/posts
  label: Blog Posts
  create: documents
  match: "**/*"
  templates:
  - blog-post
upload_dir: Portfolio
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: preview
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
