#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Running some pre-commit checks...'

# Check Prettier standards
yarn check-format ||
(
	echo 'Prettier Check Failed. Run yarn format, add changes and try commit again.';
	false;
)

# Check ESLint Standards
yarn check-lint || yarn lint-staged ||
(
	echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
	false; 
)

# Check tsconfig standards
yarn check-types ||
(
	echo 'Type Check Failed. Fix the required changes above.'
	false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ Successful Commit ✅✅✅✅'